name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pull latest changes
        run: git pull origin main

      - name: Update README with GitHub stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://api.github.com/users/kamal-ayman > user.json
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=kamal-ayman&count_private=true&show_icons=true&theme=default&token=$GH_TOKEN)" > README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m 'Updated README with GitHub stats' || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
